project:
  type: website
  output-dir: docs

website:
  title: "Lara Kobilke, Dr."
  twitter-card: true
  navbar:
    right:
      - href: index.qmd
        text: About
      - href: Experience.qmd
        text: Experience
      - href: Education.qmd
        text: Education
      - href: Teaching.qmd
        text: Teaching
      - href: Publications.qmd
        text: Publications
      - href: Presentations.qmd
        text: Presentations

format:
  html:
    theme: 
      light: solar
      dark: flatly
    css: styles.css
    toc: true


editor: visual

